
events{
    worker_connections 1024;
}

http{

    include      mime.types;
    include /etc/nginx/naxsi_rules/naxsi_core.rules;
    include /etc/nginx/naxsi_rules/blocking/*.rules;

    include /etc/nginx/naxsi_rules/custom.rules;

    default_type application/octet-stream;


    upstream backend {
        server server1:7001;
        server server2:7002;
    }

    server {
        listen 80;
        server_name localhost kudoissei;
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost kudoissei;

        ssl_certificate /etc/nginx/certs/selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/selfsigned.key;

        location / {
            include /etc/nginx/naxsi_rules/whitelists/*.rules;

            proxy_pass http://backend;  
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            DeniedUrl "/RequestDenied";
            SecRulesEnabled;
            # LearningMode;
            CheckRule "$SQL >= 4" BLOCK;
            CheckRule "$XSS >= 4" BLOCK;
        }

        location /RequestDenied { 
            return 403 "Request blocked by Naxsi WAF" ; 
        }
    }
}